---
name: Approve pull requests
on: issue_comment
jobs:
  approve:
    name: Approve a pull request (${{github.event.issue.number}})
    runs-on: ubuntu-24.04
    if: github.event.issue.pull_request && github.event.comment.body == '/approve'
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: securefix-action/approve-pr-action/validate@split-actions
        id: validate
        with:
          github_token: ${{ github.token }}
          pull_request_number: ${{ github.event.issue.number }}
      - uses: securefix-action/approve-pr-action@split-actions
        if: steps.validate.outputs.approved == 'true'
        with:
          app_id: ${{vars.DEMO_CLIENT_APP_ID}}
          app_private_key: ${{secrets.DEMO_CLIENT_PRIVATE_KEY}}
          server_repository: demo-server
