---
name: Update pull request branch by pull request comment
on: issue_comment
jobs:
  update_branch:
    runs-on: ubuntu-24.04
    if: github.event.issue.pull_request && contains(fromJSON('["/update-branch", "/ub"]'), github.event.comment.body)
    steps:
      - uses: securefix-action/update-branch-action@fix-client-input
        with:
          app_id: ${{vars.DEMO_CLIENT_APP_ID}}
          app_private_key: ${{secrets.DEMO_CLIENT_PRIVATE_KEY}}
          server_repository_name: demo-server
